<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-QDVapp-5478112e-537b-4e57-b59a-9ee5cc35c1ab</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
        <PackageReference Include="MimeKit" Version="4.17.0" />
        <PackageReference Include="QuestPDF" Version="2026.8.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\files\AvancementOF\" />
      <Folder Include="wwwroot\files\AtelierProjetsUsine\" />
    </ItemGroup>

    <ItemGroup>
      <None Include="certs\**\*.pem" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
